version: "3.8"
services:
    django: &django
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "/scripts/django-entrypoint.sh"
        volumes:
            - .:/project
            - static_volume:/app/var/static
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - postgres

    bot:
        <<: *django
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "python manage.py startbot"
        volumes:
            - .:/project
            - static_volume:/app/var/static
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - postgres

    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - 5432:5432

    nginx:
        image: nginx:latest
        volumes:
            - static_volume:/app/var/static
            - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - django

    celery:
        <<: *django
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/project
        command: bash -c "/scripts/celery-entrypoint.sh"
        ports: []
        depends_on:
            - redis

    celery-beat:
        <<: *django
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/project
        command: bash -c "/scripts/celery-beat-entrypoint.sh"
        ports: []
        depends_on:
            - redis

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
             - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
    postgres-data:
    static_volume:
