# Generated by Django 4.1.7 on 2023-03-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="user_id"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="full_name"
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="login"
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="paid")),
                (
                    "invoice_image",
                    models.ImageField(
                        blank=True,
                        upload_to="documents/invoices/<django.db.models.fields.PositiveIntegerField>",
                        verbose_name="invoice_image",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit_title",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="habit_title",
                    ),
                ),
                (
                    "habit_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="habit_score"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit",
                        to="app.client",
                        verbose_name="users",
                    ),
                ),
            ],
            options={
                "verbose_name": "habit",
                "verbose_name_plural": "habits",
            },
        ),
    ]
