# Generated by Django 4.1.7 on 2023-03-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="joined",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="joined"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="user_id"
            ),
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="created"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="created"),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="is_finished"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch",
                        to="app.client",
                        verbose_name="users",
                    ),
                ),
            ],
            options={
                "verbose_name": "batch",
                "verbose_name_plural": "batches",
            },
        ),
    ]
