# Generated by Django 4.1.7 on 2023-03-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_batch_batch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="approve_notified",
            field=models.BooleanField(default=False, verbose_name="paid"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end_date"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="start_date"
            ),
        ),
    ]
