# Generated by Django 4.1.7 on 2023-03-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_client_approve_notified_alter_batch_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="approve_notified",
            field=models.BooleanField(default=False, verbose_name="approve_notified"),
        ),
    ]
