# Generated by Django 4.1.7 on 2023-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_client_approve_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="habit_score"
            ),
        ),
    ]
